spring:
  application:
    name: user-manager
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:userdata
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true